### ISSUE TITLE
Error with your data URLs: Dropbox Error

### ISSUE THREAD

**Issue by albertvillanova** [CompGuessWhat/compguesswhat.github.io#1]
When trying to access your data URLs, we find a Dropbox error, e.g.: 
- https://www.dropbox.com/s/l0nc13udml6vs0w/compguesswhat-original.zip?dl=1
- https://www.dropbox.com/s/gd46azul7o7iip4/compguesswhat-zero_shot.zip?dl=1

CC: @aleSuglia

**Comment by aleSuglia** [comment]
@albertvillanova apologies. I'll get it sorted asap!

New links:
- https://www.dropbox.com/s/qd9wlydpkpmq8rr/compguesswhat-original.zip?dl=1
- https://www.dropbox.com/s/f5o2t7aiok7kpcm/compguesswhat-zero_shot.zip?dl=1

**Comment by albertvillanova** [comment]
We have updated the URLs of the data files and your dataset is again accessible, see: https://huggingface.co/datasets/compguesswhat
